version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser", "nodejs"]
  module_system = "es-modules"

[[transformer]]
name = "prettier"
enabled = true
